"""add maintenance type and completion time

Revision ID: 06ceeebbb833
Revises: fc848f75bb10
Create Date: 2026-08-10 18:56:24.166653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ceeebbb833'
down_revision: Union[str, Sequence[str], None] = 'fc848f75bb10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "work_orders",
        sa.Column(
            "maintenance_type",
            sa.String(length=20),
            nullable=True,
        ),
    )
    op.add_column(
        "work_orders",
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )

    op.execute(
        """
        UPDATE work_orders
        SET maintenance_type = 'corrective'
        WHERE maintenance_type IS NULL
        """
    )

    op.alter_column(
        "work_orders",
        "maintenance_type",
        existing_type=sa.String(length=20),
        nullable=False,
    )

    op.create_index(
        op.f("ix_work_orders_maintenance_type"),
        "work_orders",
        ["maintenance_type"],
        unique=False,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_maintenance_type'), table_name='work_orders')
    op.drop_column('work_orders', 'completed_at')
    op.drop_column('work_orders', 'maintenance_type')
    # ### end Alembic commands ###
