"""add failure code to work orders

Revision ID: fc848f75bb10
Revises: e6609ce8329b
Create Date: 2026-08-06 17:42:22.852461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc848f75bb10'
down_revision: Union[str, Sequence[str], None] = 'e6609ce8329b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('work_orders', sa.Column('failure_code', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_work_orders_failure_code'), 'work_orders', ['failure_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_orders_failure_code'), table_name='work_orders')
    op.drop_column('work_orders', 'failure_code')
    # ### end Alembic commands ###
